/* Generated By:JavaCC: Do not edit this line. MulaParserConstants.java */
package mula.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MulaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRING = 4;
  /** RegularExpression Id. */
  int SYMBOL = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "<STRING>",
    "<SYMBOL>",
    "\"(\"",
    "\")\"",
  };

}
